@baseUrl=http://localhost:3333/api/v2

# @name login
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "phone" : "942240594",
    "password" : "Melos@TE"
}

### Get token
@jwtToken = {{login.response.body.jwtToken}}


### create trip 
POST {{baseUrl}}/trip
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

{
    "buses": ["cmfco3d7a0006cppj1m5wfcu9","cmfco3d7k001mcppjqeqzgfkn"],
    "routeId": "cmfco5aiz046ecppjzwewtuzf",
    "tripDate" : "2025-10-15T04:00:00.000Z",
}

### create multiple trip
POST {{baseUrl}}/trip/bulk
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

[
    {"buses": ["cmfwjw0gb006tah4cq5502o1h"],"routeId": "cmfwjsp9l0008ah4cija7j5b0", "tripDate" : "2025-10-11T04:00:00.000Z"},
    {"buses": ["cmfwjw0gp0089ah4cwzhgc257","cmfwjw0h1009pah4cy8qf1ati"],"routeId": "cmfwjt9qk0009ah4ccyli09o3", "tripDate" : "2025-10-12T04:00:00.000Z"}
]

### get trips with pagination, filter, sort and search
GET {{baseUrl}}/trip?page=1&perPage=10&sortField=createdAt&sortOrder=desc
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

### search trip with routeId and tripDate
GET {{baseUrl}}/trip/search
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

{
    "routeId" : "cmg2i6t3y040lahyo3cw5c25f",
    "tripDate" : "2025-10-23"
}

### search trip with id 
GET  {{baseUrl}}/trip/cmfazocms006lcpfq9bol5nqm
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

### update trip
PATCH {{baseUrl}}/trip/cmfazocms006lcpfq9bol5nqm
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

{
    "buses": ["cmfazm3v2001gcpfqahlfbtnv","cmfazm3v6002wcpfq0jotjmx0"]
}

### delete trip with id
DELETE {{baseUrl}}/trip/cmftntnqw041fahtlrdyrr2id
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}
