@baseUrl=http://localhost:3333/api/v2

# @name login
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "phone" : "942240594",
    "password" : "Melos@TE"
}

### Get token
@jwtToken = {{login.response.body.jwtToken}}


### create trip 
POST {{baseUrl}}/trip
Content-Type: application/json
Cookie: jwtToken:{{jwtToken}}

{
    "buses": ["cmfazm3uv0000cpfqsjptl1yh","cmfazm3v2001gcpfqahlfbtnv"],
    "routeId": "cmfazmkrv005scpfql13tut9f",
    "departureTime" : "2025-09-07T04:00:00.000Z",
    "arrivalTime" : "2025-09-07T16:00:00.000Z",
    "status" : "SCHEDULED"
}

### create multiple trip
POST {{baseUrl}}/trip/bulk
Content-Type: application/json
Cookie: jwtToken:{{jwtToken}}

[
    {"buses": ["cmfbj5bvf0000nl7dvbzazjk8"],"routeId": "cmfbitxnf002snlf6twl4or4w", "departureTime" : "2025-09-11T04:00:00.000Z", "arrivalTime": "2025-09-11T04:00:00.000Z"},
    {"buses": ["cmfbj5bw5001gnl7d5xldlx4m","cmfbj5bws002wnl7dmi52cuz0"],"routeId": "cmfbitxnf002tnlf6c89f07yi", "departureTime" : "2025-09-12T04:00:00.000Z", "arrivalTime": "2025-09-12T04:00:00.000Z"}
]

### get trips with pagination, filter, sort and search
GET {{baseUrl}}/trip?page=1&perPage=10&sortField=createdAt&sortOrder=desc
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

### search trip with id 
GET  {{baseUrl}}/trip/cmfazocms006lcpfq9bol5nqm
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

### update trip
PATCH {{baseUrl}}/trip/cmfazocms006lcpfq9bol5nqm
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

{
    "buses": ["cmfazm3v2001gcpfqahlfbtnv","cmfazm3v6002wcpfq0jotjmx0"]
}

### delete trip with id
DELETE {{baseUrl}}/trip/cmfazocms006lcpfq9bol5nqm
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}
