@baseUrl=http://localhost:3333/api/v2 

# @name login
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "phone" : "977681970",
    "password" : "Melos@TE"
}

### Get token
@jwtToken = {{login.response.body.jwtToken}}

### create booking 
POST {{baseUrl}}/booking
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

{
    "tripId" : "cmfxpliv0041hcphd2ouhxo59",
    "seatId" : ["cmfxplipy03v3cphdoacf3y8q","cmfxplipy03v5cphdawdjf04v"],
    "totalAmount" : 1890
}

### get bookings with pagination, filter, sort and search
GET {{baseUrl}}/booking?page=1&perPage=10&sortField=createdAt&sortOrder=desc
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}


### search booking with id 
GET  {{baseUrl}}/booking/cmfco83fg0479cppjcx1lmzut
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}


### update booking with booking id
PATCH {{baseUrl}}/booking/cmfb6v0690001cp21tvqowzhm
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}

{
    "totalAmount" : 4000
}

### delete booking with booking id
DELETE {{baseUrl}}/booking/
Content-Type: application/json
Cookie: jwtToken={{jwtToken}}